# name: Build and Push ETL Scripts Image

# on:
#   push:
#     branches:
#       - main
#       - dev
#     paths:
#       - "etl_scripts/**"

# jobs:
#   build-and-push:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: read

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v3

#       - name: Log in to Docker Hub
#         uses: docker/login-action@v3
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}

#       - name: Build and push ETL Scripts Docker image
#         run: |
#           if [ -f "etl_scripts/Dockerfile.etl_scripts" ]; then
#             IMAGE_NAME="your-dockerhub-username/etl_scripts"
#             docker build -t $IMAGE_NAME:latest -f etl_scripts/Dockerfile.etl_scripts etl_scripts
#             docker push $IMAGE_NAME:latest
#           else
#             echo "Dockerfile.etl_scripts not found! Skipping build."
#           fi
