# 이후 추가할지도 모름. 레포가 삭제 시도가 감지될 경우 레포를 자동으로 fork



# name: Protect Repo

# on:
#   repository:
#     types: [deleted]

# jobs:
#   restore:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Restore repository
#         run: |
#           curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
#           -H "Accept: application/vnd.github.v3+json" \
#           https://api.github.com/orgs/YOUR_ORG/repos \
#           -d '{"name":"backup-YOUR_REPO", "private":true}'
