# name: PySpark Code Validation

# on:
#   pull_request:
#     branches:
#       - main
#       - dev
#     paths:
#       - "spark/**"

# jobs:
#   test-spark:
#     name: Run PySpark Tests
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4

#       - name: Set up Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: "3.10"

#       - name: Install PySpark
#         run: pip install pyspark

#       - name: Run PySpark Tests
#         run: pytest spark/tests/
